---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Janna Skinner jns2978

#### Introduction 

The datasets I am using are lincoln_weather and SeatacWeather which I was able to find on the R data sets and packages. With these datasets I can compare and constrast weather trends in the Lincoln, Nebraska area as well as in the Seatlle-Tacoma Area. The variables will be month, year, max temp, min temp, and precipitation. While each of the datasets have more extensive variables I think the ones I chose will be beneficial in discovering any weather patterns with the associated areas. With these variables it will be interesting to find out if there is any correlation between the temperature or precipitation during certain times of the year in two very different geographical regions. 

```{R}
library(tidyverse)
library(plyr)
library(dplyr)
packageVersion("dplyr")

library(ggridges)
lincoln_weather

library(latticeExtra)
SeatacWeather

```

#### Tidying: Reshaping

Since the datasets are already tidy I will be utilizing pivot longer/wider later on in the project at the merging step. To reshape my code I first started with the Lincoln weather data and separated the CST column so I could have a Year and Month column that would fit in nicely with the Seatac data. Next, I selected the variables I thought would be most useful to have in the dataset and removed the other unnecessary data. The I made sure to change the variable type of Year so it would match the other dataset. For the Seatac weather data, again I only selected the necessary variables that matched the other dataset and then I renamed the month observations to their number representatives so it would fit it nicely with the other dataset's variable types. Lastly, I made sure all the variable types matched for each data set and created a new column for the location of the weather stats.

```{R}
lincoln_weather <- lincoln_weather %>% separate(CST, c("Year", "Month", 
    "Day"), sep = "-")
lincoln_weather <- lincoln_weather %>% select(Year, Month, `Max Temperature [F]`, `Min Temperature [F]`, `Precipitation [In]`)
lincoln_weather <- lincoln_weather  %>% dplyr::rename(MaxTemp = 'Max Temperature [F]', MinTemp = 'Min Temperature [F]', Precipitation = 'Precipitation [In]')
lincoln_weather <- transform(lincoln_weather, Year = as.integer(Year))
lincoln_weather <- transform(lincoln_weather, Month = as.integer(Month))
lincoln_weather <- transform(lincoln_weather, Precipitation = as.numeric(Precipitation))
lincoln_weather <- lincoln_weather %>% mutate(Place = "Lincoln")

SeatacWeather <- SeatacWeather %>% select(year, month, max.temp, min.temp, precip)
SeatacWeather <- SeatacWeather %>% mutate(month = stringr::str_replace(month, 
    "January", "1"))
SeatacWeather <- SeatacWeather %>% mutate(month = stringr::str_replace(month, 
    "February", "2"))
SeatacWeather <- SeatacWeather %>% mutate(month = stringr::str_replace(month, 
    "March", "3"))
SeatacWeather <- SeatacWeather %>% dplyr::rename(Year = 'year', Month = 'month')
SeatacWeather <- SeatacWeather %>% mutate(place = "Sea-Tac")
SeatacWeather <- transform(SeatacWeather, Month = as.integer(Month))
```

    
#### Joining/Merging

```{R}
Weather <- full_join(lincoln_weather, SeatacWeather, by = c("Year", "Month"))

Weather <- Weather %>% select(Month, Year, MaxTemp, max.temp, MinTemp, min.temp, Precipitation, precip, Place, place)
Weather <- Weather %>% pivot_longer(3:4,names_to="names", values_to="MaxTemp")
Weather <- Weather %>% pivot_longer(3:4,names_to="names2", values_to="MinTemp")
Weather <- Weather %>% pivot_longer(3:4,names_to="names3", values_to="Precip")
Weather <- Weather %>% pivot_longer(3:4,names_to="names4", values_to="Location")
Weather <- Weather %>% select(-names, -names2, -names3, -names4)
Weather <- Weather %>% na.omit()
Weather <- Weather %>% dplyr::rename(Precipitation = 'Precip')
Weather <- Weather %>% select(Location, Month, Year, MaxTemp, MinTemp, Precipitation)

```

In the Lincoln data there are 366 observations and all of them are unique. In the Seatac data there are 90 observations and all the rows are unique as well. The datasets do not have any of the same data entry observations in common. This means that the Lincoln data has 366 observations that the Seatac data does not have, and the Seatac data has 90 observations that the Lincoln data does not contain.

I used full_join to combine these data sets so that no records or observations would be lost since they have data for different dates. The joined size of the data sets has 456 rows which displays how the two data sets were simply added together with no data, rows, or observations lost.

After joining I made sure to tidy the data so that each observation had a designated row with the maximum and minimum temperatures, amount of precipitation, location it was recorded, and the month and year. After tidying the joined data sets and removing all rows with NAs 89 rows were lost since the new total number of observations is 367.

####  Wrangling

```{R}
Weather <- Weather %>% mutate(MedianTemp = ((MaxTemp + MinTemp)/2) )
Weather <- Weather %>% mutate(Location = str_remove_all(Location, "[-]"))

Weather %>% summarise(Avg = mean(MaxTemp), SD= sd(MaxTemp), Min = min(MaxTemp), Max = max(MaxTemp), UniqueTemps = n_distinct(MaxTemp) )
Weather %>% summarise(Avg = mean(MinTemp), SD= sd(MinTemp), Min = min(MinTemp), Max = max(MinTemp), UniqueTemps = n_distinct(MinTemp))
Weather %>% summarise(Avg = mean(Precipitation), SD= sd(Precipitation), Min = min(Precipitation), Max = max(Precipitation), UniqueAmounts = n_distinct(Precipitation))

Weather %>% group_by(Location) %>% summarise(Avg = mean(MedianTemp), SD= sd(MedianTemp), Min = min(MedianTemp), Max = max(MedianTemp), UniqueTemps = n_distinct(MedianTemp) )
Weather %>% group_by(Month) %>% summarise(Avg = mean(MedianTemp), SD= sd(MedianTemp), Min = min(MedianTemp), Max = max(MedianTemp), UniqueTemps = n_distinct(MedianTemp) )

Weather %>% group_by(Location) %>% dplyr::summarize(count = n())
Weather %>% group_by(Month) %>% dplyr::summarize(count = n()) 
Weather %>% group_by(Location, Month) %>% dplyr::summarize(count = n()) 

Weather %>% filter(Month == '1') %>% summarise(Avg = mean(MedianTemp), SD= sd(MedianTemp), Min = min(MedianTemp), Max = max(MedianTemp), UniqueTemps = n_distinct(MedianTemp) )
Weather %>% filter(Month == '6') %>% summarise(Avg = mean(MedianTemp), SD= sd(MedianTemp), Min = min(MedianTemp), Max = max(MedianTemp), UniqueTemps = n_distinct(MedianTemp) )

Weather %>% filter(Location == "Lincoln") %>% select(Precipitation, MinTemp, MaxTemp) %>% arrange(desc(Precipitation))
Weather %>% filter(Location == "SeaTac") %>% select(Precipitation, MinTemp,MaxTemp) %>% arrange(desc(Precipitation))
```

```{R}
library(knitr)
library(gt)

Weather %>% summarize_at(c(4:7) , .funs=list(mean=mean,sd=sd, min=min, max=max, unique = n_distinct)) %>% pivot_longer(1:20,names_to="names", values_to="values") %>% separate(names, into=c("name","stat")) %>% pivot_wider(names_from = 'name', values_from = 'values') -> table1

table1 %>% gt %>% tab_header(title=md("**Summary Statistics**"), subtitle=md("A table of my `Weather` summary statistics")) %>% tab_spanner(label="Variables", columns=c("stat","MaxTemp","MinTemp","Precipitation","MedianTemp"))
```
First, a new variable was created by using the existing minimum and maximum temperatures. Next, any location name that had a hyphen was taken out. For example, Sea-Tac is now SeaTac. Then, summary statistics were calculated for the numeric variables of MaxTemp, MinTemp, and Precipitation. The mean, sd, minimum, maximum and distinct values were calculated. The same summary statistics were calculated for the Median Temp depending on the grouping by Location or Month. The number of observations per location was calculated. 305 in Lincoln and in 62 SeaTac. The number of observations per month was also calculated. Then the number of observations per month at each location was calculated.

Next, I compared the Median Temperature statistics for the winter in Month 1 and the summer at Month 6. The avg, min, and max and significant differences as predicted. Lastly, I compared the difference of precipitation in Lincoln and SeaTac. I was surprised to see that Lincoln had a higher maximum amount of precipitation. However, this observation could be due to the fact that Lincoln has more data entries than SeaTac.


#### Visualizing

```{R}
Weather %>% ggplot(mapping = aes(x = Month, y = MaxTemp, color = Location))  + geom_point() +geom_smooth() + ylab("Max Temperature [F]") + scale_x_continuous(breaks = seq(0, 12, 1)) + ggtitle("Max Temperatures based on Month") + theme(plot.title = element_text(size = rel(2)))
```

The plot shows the gradual change in the maximum temperatures over the course of 12 months. The red shows the Lincoln location while the teal represents SeaTac. This shows that there is an increase in temperature from January to March in both locations. For Lincoln, it appears that the peak in max temperature occurs in July. 

```{R}
Weather %>% ggplot(mapping = aes(x = Month, y = MinTemp, color = Location))  + geom_point() + geom_line() +facet_wrap(~Year) + ylab("Min Temperature [F]") + scale_x_continuous(breaks = seq(0, 12, 1)) + ggtitle("Min Temperatures based on Month and Location") + theme(axis.line = element_line(size = 3, color = "grey"))
```

This plot shows the minimum temperatures changing every month for the two different locations side by side. On the left, SeaTac is represented by teal. On the right, Lincoln is represented by the red. Having the facet side by side is beneficial to recognize how the minimum temperature in Lincoln for January - March is significantly higher than Lincoln's minimum temperatures for those months.

```{R}
Weather %>% ggplot(mapping = aes(x = Month, y = Precipitation, fill = Location)) + geom_bar(stat = "summary", fun = mean) + ylab("Precipitation [In]") + scale_x_continuous(breaks = seq(0, 12, 1)) + ggtitle("Precipitation based on Month and Location") + geom_errorbar(stat = "summary", fun.data = mean_se, width = 0.25) + scale_fill_brewer() + theme(panel.background = element_rect(fill = "white", color = "grey"))
```

This bar plot shows the number of inches of precipitation per month in Lincoln and SeaTac. For both locations there is significantly more rainfall in January than February or March. Additionally, it is clear that Lincoln has more rainfall than SeaTac in January-March. There is the highest amount of precipitation in Lincoln in April and the least in October.






